### ISSUE TITLE
Checklist: V2 Launch

### ISSUE THREAD

**Issue by gasi** [zoomhub/zoomhub#118]
- [x] Set up staging environment:
  - [x] Create Ansible playbook.
  - [x] Create clone of existing block storage with production data.
- [x] Reset production server.
- [x] Set up admin machine:
  - [x] Set up Splunk.
- [x] Test Google Analytics.
- [x] Write tests.
- [x] Ensure CI deploys `master` to production and other branches to staging.
- [x] Add support for JSONP, i.e. ?callback=…`.
- [x] Add support for non-RESTful responses, i.e. `?format=…`.
