### ISSUE TITLE
Accept new content again

### ISSUE THREAD

**Issue by aseemk** [zoomhub/zoomhub#93]
Realized we didn't really have an issue to track this; opening this one.

Related issues and pre-reqs:
- [x] #60 to hook up tile uploads to Cloud Files after generation
- [x] #89, #91 to convert all of our remaining _existing_ content
- [x] #63 to move to a proper database (no way we can scale w/ flat files)
- [ ] #8 potentially to add a queue (for scale, to let us recover from errors, etc.)
- [ ] #42 to properly track and convey `ready`/`failed`/`progress`

**Comment by gasi** [comment]
We now do for uploads! ⬆️
